#!/usr/bin/env bash
# Load dev standard shell library
# shellcheck source=../lib/funcs.sh
. "$(dirname "$0")/../lib/funcs.sh"
need_progs less

os=$(uname -s)
find "${HOMEBREW_LOGS}/$1" -type f -print0 | sort -z | xargs -0 less
