#!/usr/bin/env bash
#:`brew nuke-branch` *branch* ...
#:    Remove local and remote copies of *branch*
#:
#:    Environment variables:
#:      HOMEBREW_GITHUB_UPSTREAM : name of Git remote to operate on (required)

. "$(dirname "$0")/../lib/funcs.sh"

[[ -n $HOMEBREW_GITHUB_UPSTREAM ]] || fatal "HOMEBREW_GITHUB_UPSTREAM not set"
if mainbranch=$(git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null); then
  mainbranch=${mainbranch##*/}
else
  fatal "Not in Git repo"
fi
currbranch=$(git branch --show-current)
if [[ $# -eq 0 ]]; then
  need_progs gum
  readarray -t branches < <(git branch --color=never | grep -Ewv 'master|stable' | tr -d '* ')
  readarray -t args < <(gum choose --selected="*" "${branches[@]}")
  set -- "${args[@]}"
fi
if [[ $# -gt 0 ]]; then
  for b in "$@"; do
    [[ $b == "$mainbranch" ]] && continue
    [[ $b == "$currbranch" ]] && git checkout "${mainbranch}"
    # Check for remote branch
    info "$b"
    [[ -n "$(git ls-remote "${HOMEBREW_GITHUB_UPSTREAM}" "$b")" ]] && cmd git push -d "${HOMEBREW_GITHUB_UPSTREAM}" "$b"
    [[ -n "$(git branch --list "$b")" ]] && cmd git branch -D "$b"
  done
  git branch -a
fi
